# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xuehsaneg.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtWidgets, QtCore, QtGui
from PyQt5.QtWidgets import *
import sys



class Stu_Window(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.retranslateUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.setWindowTitle("学生信息管理系统V11.2.3")                             # 设置窗口标题
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)  # 自定义图标
        self.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 791, 571))
        self.tabWidget.setObjectName("tabWidget")
        self.chaxunchengji = QtWidgets.QWidget()
        self.chaxunchengji.setObjectName("chaxunchengji")
        self.label = QtWidgets.QLabel(self.chaxunchengji)
        self.label.setGeometry(QtCore.QRect(80, 50, 141, 51))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.chaxunchengji)
        self.pushButton.setGeometry(QtCore.QRect(380, 60, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.chaxunchengji)
        self.textEdit.setGeometry(QtCore.QRect(200, 60, 141, 31))
        self.textEdit.setObjectName("textEdit")
        self.tableWidget = QtWidgets.QTableWidget(self.chaxunchengji)
        self.tableWidget.setGeometry(QtCore.QRect(0, 140, 781, 81))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.pushButton_3 = QtWidgets.QPushButton(self.chaxunchengji)
        self.pushButton_3.setGeometry(QtCore.QRect(110, 260, 100, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.chaxunchengji)
        self.pushButton_4.setGeometry(QtCore.QRect(380, 260, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget.addTab(self.chaxunchengji, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(100, 60, 141, 21))
        self.label_2.setObjectName("label_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_2.setGeometry(QtCore.QRect(220, 60, 181, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(440, 60, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 140, 781, 91))
        self.tableWidget_2.setRowCount(1)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(130, 270, 120, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_6.setGeometry(QtCore.QRect(360, 270, 93, 28))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(10, 240, 271, 21))
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("MainWindow", "请输入您的学号:"))
        self.pushButton.setText(_translate("MainWindow", "查询"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "学号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "班级"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "姓名"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "数学分析"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "大学物理"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "近现代史纲要"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "高级程序设计"))
        self.pushButton_3.setText(_translate("MainWindow", "确认并退出"))
        self.pushButton_4.setText(_translate("MainWindow", "退出"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.chaxunchengji), _translate("MainWindow", "查询成绩"))
        self.label_2.setText(_translate("MainWindow", "请输入您的学号:"))
        self.pushButton_2.setText(_translate("MainWindow", "查询"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "学号"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "班级"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "姓名"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "性别"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "籍贯"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "政治面貌"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "职位"))
        self.pushButton_5.setText(_translate("MainWindow", "确认修改并退出"))
        self.pushButton_6.setText(_translate("MainWindow", "退出"))
        self.label_3.setText(_translate("MainWindow", "可在表格修改信息,修改后请点击确认"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "查询信息"))


        # 以上的代码是描述界面的，是自动生成的，可根据自己需要来改
        # 下面的代码是自己完成的

        # 把按钮与相应的事件连接起来
        self.pushButton.clicked.connect(lambda:self.findchengji())
        self.pushButton_2.clicked.connect(lambda:self.findxinxi())
        self.pushButton_5.clicked.connect(lambda:self.xiugai())
        self.pushButton_3.clicked.connect(lambda: self.sys.exit())
        self.pushButton_4.clicked.connect(lambda: self.sys.exit())
        self.pushButton_6.clicked.connect(lambda: self.sys.exit())


    def findchengji(self):
        ls = []
        i = 0
        fo = open("test.txt", "r")
        for line in fo:
            ls.append(line)
        fo.close()
        for item in ls:
            ls[i] = ls[i].split(" ")
            i = i + 1
        print(111)
        x = 0
        xuehao1=self.textEdit.toPlainText() # 此处获取查询成绩
        for it in ls:
            if xuehao1 == ls[x][0]:

                item=QTableWidgetItem(ls[x][0])
                self.tableWidget.setItem(0,0, item)
                item = QTableWidgetItem(ls[x][1])
                self.tableWidget.setItem(0, 1, item)
                item = QTableWidgetItem(ls[x][2])
                self.tableWidget.setItem(0, 2, item)
                item = QTableWidgetItem(ls[x][4])
                self.tableWidget.setItem(0, 3, item)
                item = QTableWidgetItem(ls[x][5])
                self.tableWidget.setItem(0, 4, item)
                item = QTableWidgetItem(ls[x][6])
                self.tableWidget.setItem(0, 5, item)
                item=QTableWidgetItem(ls[x][7])
                self.tableWidget.setItem(0,6, item)

                 # 此处展示数据

                break
            x = x + 1
        if x == len(ls):
            reply = QMessageBox.information(self, "错误", "无此学号")
            print(reply)



    def findxinxi(self):
        ls = []
        fo = open("test.txt", "r")
        for line in fo:
            ls.append(line)
        fo.close()
        for k in range(len(ls)):
            ls[k] = ls[k].split(" ")
        xuehao2 = self.textEdit_2.toPlainText()  # 此处获取查询成绩


        global i
        i=0
        for it in ls:
            if xuehao2 == ls[i][0]:  # 此处做显示数据
                item = QTableWidgetItem(ls[i][0])
                self.tableWidget_2.setItem(0, 0, item)
                item = QTableWidgetItem(ls[i][1])
                self.tableWidget_2.setItem(0, 1, item)
                item = QTableWidgetItem(ls[i][2])
                self.tableWidget_2.setItem(0, 2, item)
                item = QTableWidgetItem(ls[i][3])
                self.tableWidget_2.setItem(0, 3, item)
                item = QTableWidgetItem(ls[i][8])
                self.tableWidget_2.setItem(0, 4, item)
                item = QTableWidgetItem(ls[i][9])
                self.tableWidget_2.setItem(0, 5, item)
                item = QTableWidgetItem(ls[i][10])
                self.tableWidget_2.setItem(0, 6, item)

                break
            i = i + 1

        if i == len(ls):
            reply = QMessageBox.information(self, "错误", "无此学号")
            print(reply)

    def xiugai(self):
        ls = []
        fo = open("test.txt", "r")
        for line in fo:
            ls.append(line)
        fo.close()
        for k in range(len(ls)):
            ls[k] = ls[k].split(" ")
        m=0
        global i
        if i<len(ls):

            a=self.tableWidget_2.item(0, 0).text()
            b=self.tableWidget_2.item(0,1).text()
            c = self.tableWidget_2.item(0, 2).text()
            d = self.tableWidget_2.item(0, 3).text()
            e = self.tableWidget_2.item(0, 4).text()
            f = self.tableWidget_2.item(0, 5).text()
            g = self.tableWidget_2.item(0, 6).text()
            if a=="" or b=="" or c=="" or d=="" or e=="" or f=="" or g=="":
                m=1
        if m == 0:
            ls[i][0]=a
            ls[i][1] =b
            ls[i][2] =c
            ls[i][3] = d
            ls[i][8] = e
            ls[i][9] = f
            t = g
            if t[-1] != '\n':
                t = t + '\n'
            ls[i][10] = t
            fom = open("test.txt", "w+")
            i=0
            for io in ls:
                ls[i][0] = ls[i][0] + " "
                ls[i][1] = ls[i][1] + " "
                ls[i][2] = ls[i][2] + " "
                ls[i][3] = ls[i][3] + " "
                ls[i][4] = ls[i][4] + " "
                ls[i][5] = ls[i][5] + " "
                ls[i][6] = ls[i][6] + " "
                ls[i][7] = ls[i][7] + " "
                ls[i][8] = ls[i][8] + " "
                ls[i][9] = ls[i][9] + " "
                i = i + 1
            ks = 0
            for pp in ls:
                fom.writelines(ls[ks])
                ks = ks + 1
            fom.seek(0)
            fom.close()

    def msg(self):
        reply = QMessageBox.information(self,"错误","无此学号")
        print(reply)




if __name__ == '__main__':

    app = QApplication(sys.argv)
    MainWindow1 = Stu_Window()
    MainWindow1.show()
    sys.exit(app.exec_())






