
# Form implementation generated from reading ui file 'aaaaaaauntitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
import sys


class Tea_Window(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.retranslateUi(self)


    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1013, 589)
        self.setWindowTitle("学生信息管理系统V11.2.3")                                             #设置窗口标题
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)        #自定义图标
        Form.setWindowIcon(icon)
        Form.setMinimumSize(QtCore.QSize(1013, 589))                                             #固定窗口大小
        Form.setMaximumSize(QtCore.QSize(1013, 589))
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1011, 581))
        self.tabWidget.setStyleSheet("font: 12pt \"AcadEref\";")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(0, 60, 1001, 491))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setRowCount(21)
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setObjectName("tableWidget")
        self.cbbox_see_class = QtWidgets.QComboBox(self.tab)
        self.cbbox_see_class.setGeometry(QtCore.QRect(320, 20, 141, 31))
        self.cbbox_see_class.setObjectName("cbbox_see_class")
        self.cbbox_see_class.addItem("")
        self.cbbox_see_class.addItem("")
        self.cbbox_see_class.addItem("")
        self.btn_see_check = QtWidgets.QPushButton(self.tab)
        self.btn_see_check.setGeometry(QtCore.QRect(520, 20, 91, 31))
        self.btn_see_check.setObjectName("btn_see_check")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(190, 20, 121, 21))
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.tab, "")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.formLayoutWidget = QtWidgets.QWidget(self.widget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 291, 380))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.cbBox_add_class = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cbBox_add_class.setObjectName("cbBox_add_class")
        self.cbBox_add_class.addItem("")
        self.cbBox_add_class.addItem("")
        self.cbBox_add_class.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cbBox_add_class)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.edt_add_name = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.edt_add_name.setObjectName("edt_add_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edt_add_name)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.edt_add_num = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.edt_add_num.setObjectName("edt_add_num")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.edt_add_num)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.cbbox_add_gen = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cbbox_add_gen.setObjectName("cbbox_add_gen")
        self.cbbox_add_gen.addItem("")
        self.cbbox_add_gen.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cbbox_add_gen)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.edt_add_one = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.edt_add_one.setObjectName("edt_add_one")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.edt_add_one)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.edt_add_two = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.edt_add_two.setObjectName("edt_add_two")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.edt_add_two)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.edt_add_three = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.edt_add_three.setObjectName("edt_add_three")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.edt_add_three)
        self.label_21 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.edt_add_four = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.edt_add_four.setObjectName("edt_add_four")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.edt_add_four)
        self.btn_add = QtWidgets.QPushButton(self.widget)
        self.btn_add.setGeometry(QtCore.QRect(110, 410, 121, 41))
        self.btn_add.setObjectName("btn_add")
        self.tabWidget.addTab(self.widget, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 297, 121))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.edt_change_num = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.edt_change_num.setObjectName("edt_change_num")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edt_change_num)
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.cbBox_add_subj_2 = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.cbBox_add_subj_2.setObjectName("cbBox_add_subj_2")
        self.cbBox_add_subj_2.addItem("")
        self.cbBox_add_subj_2.addItem("")
        self.cbBox_add_subj_2.addItem("")
        self.cbBox_add_subj_2.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cbBox_add_subj_2)
        self.label_20 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.edt_change_score = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.edt_change_score.setObjectName("edt_change_score")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.edt_change_score)
        self.btn_change = QtWidgets.QPushButton(self.tab_2)
        self.btn_change.setGeometry(QtCore.QRect(120, 150, 93, 32))
        self.btn_change.setObjectName("btn_change")
        self.tabWidget.addTab(self.tab_2, "")


        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

        #把按钮与相应的事件连接起来
        self.btn_see_check.clicked.connect(self.Check_score)
        self.btn_add.clicked.connect(self.Add_score)
        self.btn_change.clicked.connect(self.Change_score)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.cbbox_see_class.setItemText(0, _translate("Form", "信息工程7班"))
        self.cbbox_see_class.setItemText(1, _translate("Form", "信息工程8班"))
        self.cbbox_see_class.setItemText(2, _translate("Form", "信息工程9班"))
        self.btn_see_check.setText(_translate("Form", "查询"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">请选择班级：</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "查询班级成绩"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">请选择班级：</span></p></body></html>"))
        self.cbBox_add_class.setItemText(0, _translate("Form", "信息工程7班"))
        self.cbBox_add_class.setItemText(1, _translate("Form", "信息工程8班"))
        self.cbBox_add_class.setItemText(2, _translate("Form", "信息工程9班"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">姓名：</span></p></body></html>"))
        self.label_11.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">学号：</span></p></body></html>"))
        self.label_12.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">性别：</span></p></body></html>"))
        self.cbbox_add_gen.setItemText(0, _translate("Form", "男"))
        self.cbbox_add_gen.setItemText(1, _translate("Form", "女"))
        self.label_14.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">请输入成绩：</span></p></body></html>"))
        self.label_15.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">数学分析：</span></p></body></html>"))
        self.label_16.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">大学物理：</span></p></body></html>"))
        self.label_18.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">近现代史：</span></p></body></html>"))
        self.label_21.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">C++：</span></p></body></html>"))
        self.btn_add.setText(_translate("Form", "录入"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("Form", "录入学生成绩"))
        self.label_17.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">请输入学号：</span></p></body></html>"))
        self.label_19.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">请选择科目：</span></p></body></html>"))
        self.cbBox_add_subj_2.setItemText(0, _translate("Form", "数学分析"))
        self.cbBox_add_subj_2.setItemText(1, _translate("Form", "大学物理"))
        self.cbBox_add_subj_2.setItemText(2, _translate("Form", "近现代史"))
        self.cbBox_add_subj_2.setItemText(3, _translate("Form", "C++"))
        self.label_20.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">请输入成绩：</span></p></body></html>"))
        self.btn_change.setText(_translate("Form", "修改"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "修改学生成绩"))

        # 以上的代码是描述界面的，除了有注释的部分，都是自动生成的，可根据自己需要来改
        # 下面的代码是自己完成的

         #定义查看成绩函数
    def Check_score(self):
        cla_num = self.cbbox_see_class.currentText()
        filename = ""
        ls = []
        if cla_num == "信息工程7班":
            filename = "score_class7.txt"
        elif cla_num == "信息工程8班":
            filename = "score_class8.txt"
        elif cla_num == "信息工程9班":
            filename = "score_class9.txt"
        for k in range(20):                                   #先清空表格
            for j in range(8):
                newitem = QTableWidgetItem("")
                self.tableWidget.setItem(k, j, newitem)
        file = open(filename, "r")
        row = 0
        for line in file:
            line = line.replace("\n", "")
            ls = line.split(" ")
            for coln in range(len(ls)):
                newitem = QTableWidgetItem(ls[coln])
                self.tableWidget.setItem(row, coln, newitem)
            row = row + 1
        file.close()

        #定义添加成绩函数
    def Add_score(self):
        ls_add = []
        filename = ""
        stu_cla = self.cbBox_add_class.currentText()
        stu_name = self.edt_add_name.text().strip()
        stu_num = self.edt_add_num.text().strip()
        stu_gen = self.cbbox_add_gen.currentText()
        stu_subj_one = self.edt_add_one.text().strip()
        stu_subj_two = self.edt_add_two.text().strip()
        stu_subj_three = self.edt_add_three.text().strip()
        stu_subj_four = self.edt_add_four.text().strip()


        ls_item = ["姓名或学号","姓名或学号","性别","成绩","成绩","成绩","成绩"]
        ls_add.append(stu_num)
        ls_add.append(stu_name)
        ls_add.append(stu_gen)
        ls_add.append(stu_subj_one)
        ls_add.append(stu_subj_two)
        ls_add.append(stu_subj_three)
        ls_add.append(stu_subj_four)

        weh_empty = False               #以weh_empty标记输入是否为空的变量，为空则不进行后面的操作
        for i in range(len(ls_add)):
            if ls_add[i] == "":
                weh_empty = True
                QMessageBox.warning(self, '警告', ls_item[i]+'不能为空！', QMessageBox.Yes | QMessageBox.No, QMessageBox.Yes)
                break

        if weh_empty == False:
            whe_repe = False                         # 标记待录入学号是否与已有学号重复的变量，为Flase则表示没有重复
                                                     # 不允许学号重复，但允许姓名重复
            if stu_cla == "信息工程7班":
                filename = "score_class7.txt"
            elif stu_cla == "信息工程7班":
                filename = "score_class8.txt"
            elif stu_cla == "信息工程7班":
                filename = "score_class8.txt"

            file = open(filename, "r")
            for line in file:
                line = line.replace("\n", "")
                ls = line.split(" ")
                if stu_num == ls[0]:
                    whe_repe = True
                    QMessageBox.warning(self, '警告', '该学号已存在，请勿重复录入！', QMessageBox.Yes | QMessageBox.No, QMessageBox.Yes)
                    break
            file.close()

            if whe_repe == False:
                file = open(filename, "a+")
                file.write("\n")
                for i in range(6):
                    file.write(ls_add[i] + " ")
                file.write(ls_add[6])
                file.close()

                file = open(filename, "r")
                row = 0
                for line in file:
                    line = line.replace("\n", "")
                    ls = line.split(" ")
                    for coln in range(len(ls)):
                        newitem = QTableWidgetItem(ls[coln])
                        self.tableWidget.setItem(row, coln, newitem)
                    row = row + 1
                file.close()
                QMessageBox.information(self, '消息', '录入成功！再次点击查询可查看已更新成绩！', QMessageBox.Yes | QMessageBox.No,QMessageBox.Yes)

        #定义修改成绩函数
    def Change_score(self):
        filename = ""
        stu_num = self.edt_change_num.text().strip()
        cha_score = self.edt_change_score.text().strip()
        stu_subj_Index = self.cbBox_add_subj_2.currentIndex()

        weh_empty = False
        if cha_score == "" or stu_num == "":
            weh_empty = True
            QMessageBox.warning(self, '警告', '学号或成绩不能为空！', QMessageBox.Yes | QMessageBox.No, QMessageBox.Yes)
        if weh_empty == False :           #如果学号、成绩不空
            if len(stu_num) != 6 :
                QMessageBox.warning(self, '警告', '学号应为6位数字！', QMessageBox.Yes | QMessageBox.No, QMessageBox.Yes)
            elif stu_num[2:4] not in ["21","22","23"] :
                QMessageBox.warning(self, '警告', '该学号不合法！第三四位应为21，22或23!', QMessageBox.Yes | QMessageBox.No, QMessageBox.Yes)
            else :
                if stu_num[2:4] =="21":
                    filename = "score_class7.txt"
                elif stu_num[2:4] =="22":
                    filename = "score_class8.txt"
                elif stu_num[2:4] == "23":
                    filename = "score_class9.txt"
                file = open(filename,"r+")
                ls1 = []
                ls2 = []
                row = 0
                find_num = False                                         #标记是否找到学号
                for oldline in file:
                    newline = oldline.replace("\n", "")
                    ls1 = newline.split(" ")
                    if ls1[0] != stu_num :                                #如果找到了要修改的成绩所在行
                        ls2.append(oldline)
                    else:
                        ls1[stu_subj_Index+3] = cha_score                  #成绩所在列的索引为成绩在comboBox的索引加3
                        str1 = " ".join(ls1)
                        ls2.append(str1)
                        find_num = True                                  #标记变为True
                        newitem = QTableWidgetItem(cha_score)
                        self.tableWidget.setItem(row, stu_subj_Index+3, newitem)        #把修改后的成绩展示到表格
                        QMessageBox.information(self, '消息', '修改成功！成绩已更新！', QMessageBox.Yes | QMessageBox.No,
                                                QMessageBox.Yes)
                    row = row + 1
                file.close()
                file = open(filename, "w+")
                for data in ls2:
                    file.write(data)
                file.close()


                if find_num == False :
                    QMessageBox.warning(self, '警告',"该学号不存在！", QMessageBox.Yes | QMessageBox.No,
                                        QMessageBox.Yes)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    main_login = Tea_Window()
    main_login.show()
    sys.exit(app.exec_())
